name: CI
on: 
  push:
    branches: [ main ]
jobs:
  deploy:
    name: "Deploy to dev"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/dev.key
          chmod 600 ~/.ssh/dev.key
          cat >>~/.ssh/config <<END
          Host dev
            HostName $SSH_HOST
            User root
            Port 22
            IdentityFile ~/.ssh/dev.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}

      - name: Deploy from dev
        run: ssh dev 'cd /var/www/receptia_dev && git fetch && git reset --hard origin/main'

      - name: Restart app (all of pm2 unfortunately)
        run: ssh dev 'systemctl restart pm2-root.service'
